In [4]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

def img_gen_scat():
    """ Generate a random scatter chart exporting height array and pixel array
        TODO: .rand(5,1) = 5 bars with random data from zero to 1
        TODO: Add options for randomising scale, # bars, showing axis, grids, rotating labels, legends etc.
    """
    data = pd.DataFrame(data=np.random.rand(5,1), index=range(1,6), columns=['Fred'])
    #m,n = np.shape(data)
    print(data)
    plt.clf()
    plt.scatter(x=data.index.values, y=data.values.ravel(), color='k') # figsize=(10, 6))
    # Options for later from https://matplotlib.org/api/_as_gen/matplotlib.pyplot.bar.html
    # bar_width = 0.35
    # alpha = .3
    fig=plt.gcf()
    fig.set_size_inches(1, 1)
    plt.axis('off')
    fig.tight_layout()
    fig.canvas.draw()
    # grab the pixel buffer and dump it into a numpy array
    pixels = np.array(fig.canvas.renderer._renderer)[:,:,:3]
    print(pixels,data.values.ravel() )

    type(pixels)

    return pixels, data.values.ravel()


In [5]:
img_gen_scat()

       Fred
1  0.068530
2  0.278768
3  0.943663
4  0.870024
5  0.109928
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]] [0.06853024 0.27876811 0.94366288 0.87002391 0.10992795]


(array([[[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],
 
        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],
 
        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],
 
        ...,
 
        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],
 
        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],
 
        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
  